SELECT CAR_ID,TO_CHAR(AVG_D, 'FM999.0') AS AVERAGE_DURATION
FROM (
    SELECT 
    CAR_ID,
    ROUND(AVG(END_DATE-START_DATE+1),1) AS AVG_D
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
)
WHERE AVG_D >= 7
ORDER BY AVG_D DESC, CAR_ID DESC