-- 코드를 입력하세요
SELECT CAR_ID,
       TO_CHAR(AVG_DUR, 'FM9990.0') AS AVERAGE_DURATION
FROM (
    SELECT CAR_ID,
           ROUND(AVG(END_DATE - START_DATE + 1), 1) AS AVG_DUR
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
    HAVING AVG(END_DATE - START_DATE + 1) >= 7
)
ORDER BY AVG_DUR DESC, CAR_ID DESC;