-- 코드를 입력하세요
SELECT B.CATEGORY AS CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM BOOK B, BOOK_SALES S
WHERE B.BOOK_ID = S.BOOK_ID
AND '202201' = TO_CHAR(S.SALES_DATE,'YYYYMM')
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY